### ISSUE TITLE
Collect further components from electronics store

### ISSUE THREAD

**Issue by Himikid** [allancotto/PiVersus#2]
- Collect ethernet cable and buttons

**Comment by Beepister** [comment]
Booked an appointment with the Rankine 605, for Thursday 17/02/2021 at 1PM. Will collect parts then.

**Comment by Beepister** [comment]
Electronics Component Store is currently off limits and we're only allowed to pick up parcels from there.
Himikid has ordered materials from RS components and will be picking them up from the RS store in Glasgow when they arrive.

**Comment by Himikid** [comment]
All new materials have been ordered and received
