### ISSUE TITLE
Exchange Parts

### ISSUE THREAD

**Issue by Himikid** [allancotto/PiVersus#3]
Collate all hardware.

**Comment by Beepister** [comment]
Exchange of the Raspberry Pi happened with Allan a few days ago.

**Comment by Beepister** [comment]
RaspberryPi and relevant components will be passed along to Himikid for the initial setup (RasPi OS and SSH). Meeting will be arranged between Himikid and Allan.

**Comment by Himikid** [comment]
All components have been exchanged.
